### PR TITLE
Added docker support, improved ease of use, added automatic docker image build and fixed a major security threat.

### LINKED ISSUE #5: Feature request: dockerfile
Hi, this bot looks very interesting and I'd like to run it, but there's no instructions on how to launch the bot, I'm guessing that it's not too difficult, something like downloading the bot and running main.go, but just having a container would be easier.

You can automatically build and push the image to any docker repo fairly easily with GitHub actions.

Is this addition planned?

### PR DESCRIPTION
**Pull request by Kalitsune**
Fix #5, if you end up merging this request, you should create a new version tag to generate the docker initial image

### CODE REVIEW

**Review by dustin-ward — CHANGES_REQUESTED** [review]
- Extra comments in `release.yml`
- Formatting in `bot/util.go`

**Comment by Kalitsune** [comment]
sure! my bad.
it seems you've already done some formatting in util.go, I'll only fix the comments in release.yml

**Review by dustin-ward — APPROVED** [review]
Thanks!

**Comment by Kalitsune** [comment]
No problem!
Thank you for your reactivity!

It looks like the workflow failed because  of the release tag not being in the format it expected.. 
Try using the tag `v1.2.0` instead of `v1.2`
You can also remove the automatic release part (it only automatically create a release on the github repo, it doesn't do anything related with publishing the docker container)

**Comment by Kalitsune** [comment]
sure np, it can be really useful but it's a real pain to troubleshoot lol

**Comment by Kalitsune** [comment]
thank you for your time!

**Pull request merged**
