### PR TITLE
Custom data dir and kubernetes template file.

### LINKED ISSUE #10: k8s pls
pls provide k8s config ty xoxo

### PR DESCRIPTION
**Pull request by Kalitsune**
Fix #10

### CODE REVIEW

**Review by dustin-ward — CHANGES_REQUESTED** [review]
Tabs instead of spaces in `bot.go` and `main.go`

**Comment by Kalitsune** [comment]
My bad, my editor doesn't let me use tabs and goimports didn't seem to work. I'll try with gofmt.

**Review by dustin-ward — APPROVED** [review]
Thanks again for your contributions!

**Comment by Kalitsune** [comment]
sure np! It seems that the bot doesn't like when Kubernetes try to mount something to its directory so I had to add the DATA_DIR var ^^'

**Comment by Kalitsune** [comment]
Thank you for being so quick!

**Pull request merged**
